name: uget
version: git
summary: easy-to-use download manager
description: |
 Uget (formerly urlgfe) is a simple, lightweight and easy-to-use download
 manager. It provides the following features:
  * Resume downloads.
  * Queue downloads.
  * Classify downloads in categories.
  * Mozilla Firefox integration (through Flashgot plugin).
  * Clipboard monitoring.
  * Import downloads import from HTML files.
  * Batch download.

grade: stable
confinement: strict

parts:
  uget:
    source: .
    plugin: autotools
    configflags:
      - --prefix=/usr
    after:
      - desktop-gtk3
    prepare: |
      sed -i 's|Icon=uget-icon|Icon=/usr/share/icons/hicolor/64x64/apps/uget-icon\.png|' uget-gtk.desktop
    build-packages:
      - intltool
      - libappindicator3-dev
      - libcurl4-openssl-dev
      - libgstreamer1.0-dev
      - libnotify-dev
      - libssl-dev
    stage-packages:
      - aria2
      - libappindicator3-1
      - libcairo2
      - libcurl3
      - libgstreamer1.0-0
      - libnotify4
      - libpango-1.0-0
      - libpangocairo-1.0-0

apps:
  uget:
    command: bin/desktop-launch ${SNAP}/usr/bin/uget-gtk
    desktop: usr/share/applications/uget-gtk.desktop
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - unity7
      - x11
    aliases: [uget-gtk]
